"""empty message

Revision ID: 136da1a2fbf2
Revises: 2fc35b665411
Create Date: 2024-02-02 23:40:16.641252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136da1a2fbf2'
down_revision = '2fc35b665411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
